### ISSUE TITLE
Help with authentication

### ISSUE THREAD

**Issue by andreheringer** [eyedouble/couchdb#3]
Hi everyone, first of all, thank you guys for this amazing package it is looking really nice. 

I'm trying to use it inside iex for learning purposes but I'm pretty much stuck at the moment. What I'm trying to do is list all my dbs.

```
{:ok, server} = :couchdb.server_record("http://localhost:5984", [{username="admin", password="my-secret-password"}])
{:ok, {:server, "http://localhost:5984", [{"admin", "my-secret-password"}]}}

:couchdb_server.all_dbs(server)             
{:error, :unauthenticated}
```
Any help would be most appreciated. @irsanvanwel

**Comment by ivanwel** [comment]
Hi Andre,

Thanks for using CouchDB.

Please see the code snippet below to give you an idea of how to do basic auth. Further included are some SSL configs. This is not specific to this particular package. We use hackhey as a http client so refer to this project for more http related config if need be: [Hackey](https://github.com/benoitc/hackney)

```elixir
{:ok, server} =
      :couchdb.server_record(
        "https://exampleurl:5984",
        [
          {:basic_auth, {"foo", "password"}},

          {:is_ssl, true},
          # TLS 1.3
          # "TLS_AES_256_GCM_SHA384", "TLS_CHACHA20_POLY1305_SHA256", "TLS_AES_128_GCM_SHA256"
          # TLS 1.2
          # "ECDHE-ECDSA-AES128-SHA256","ECDHE-ECDSA-AES128-SHA"
          {:ssl_options,
           [
             ciphers: [
               "TLS_AES_256_GCM_SHA384",
               "TLS_CHACHA20_POLY1305_SHA256",
               "TLS_AES_128_GCM_SHA256",
               "ECDHE-ECDSA-AES128-SHA256",
               "ECDHE-ECDSA-AES128-SHA"
             ]
           ]}
        ]
      )

```
