### ISSUE TITLE
/usr/bin/ld: cannot find -lerl_interface: No such file or directory

### ISSUE THREAD

**Issue by matteoredaelli** [eyedouble/couchdb#4]
Hello 

I cannot compile this package. Does it support the latest erlang otp releases ?

I use
  Erlang/OTP 24 [erts-12.3.2.1]

The log error is

make[1]: Entering directory '/xxx/deps/couchdb'
 DEP    jiffy (1.0.1)
 DEP    hackney (1.15.2)
make[2]: Entering directory '/xxx/deps/jiffy'
CC=cc escript enc compile
Compiling c_src/decoder.c
Compiling c_src/encoder.c
Compiling c_src/jiffy.c
Compiling c_src/termstack.c
Compiling c_src/utf8.c
Compiling c_src/util.c
Compiling c_src/doubles.cc
Compiling c_src/objects.cc
Compiling c_src/double-conversion/bignum-dtoa.cc
Compiling c_src/double-conversion/bignum.cc
Compiling c_src/double-conversion/cached-powers.cc
Compiling c_src/double-conversion/diy-fp.cc
Compiling c_src/double-conversion/double-conversion.cc
Compiling c_src/double-conversion/fast-dtoa.cc
Compiling c_src/double-conversion/fixed-dtoa.cc
Compiling c_src/double-conversion/strtod.cc
/usr/bin/ld: cannot find -lerl_interface: No such file or directory

Thanks in advance
Matteo

**Comment by ivanwel** [comment]
Looks like the jiffy dependency doesn't compile. Feel free to make a PR to version bump Jiffy.On 22 Jul 2022 5:20 pm, Matteo Redaelli ***@***.***> wrote:
Hello
I cannot compile this package. Does it support the latest erlang otp releases ?
I use
Erlang/OTP 24 [erts-12.3.2.1]
The log error is
make[1]: Entering directory '/xxx/deps/couchdb'
DEP    jiffy (1.0.1)
DEP    hackney (1.15.2)
make[2]: Entering directory '/xxx/deps/jiffy'
CC=cc escript enc compile
Compiling c_src/decoder.c
Compiling c_src/encoder.c
Compiling c_src/jiffy.c
Compiling c_src/termstack.c
Compiling c_src/utf8.c
Compiling c_src/util.c
Compiling c_src/doubles.cc
Compiling c_src/objects.cc
Compiling c_src/double-conversion/bignum-dtoa.cc
Compiling c_src/double-conversion/bignum.cc
Compiling c_src/double-conversion/cached-powers.cc
Compiling c_src/double-conversion/diy-fp.cc
Compiling c_src/double-conversion/double-conversion.cc
Compiling c_src/double-conversion/fast-dtoa.cc
Compiling c_src/double-conversion/fixed-dtoa.cc
Compiling c_src/double-conversion/strtod.cc
/usr/bin/ld: cannot find -lerl_interface: No such file or directory
Thanks in advance
Matteo

**Comment by ivanwel** [comment]
Hi @matteoredaelli, let me know if you still have this compilation issue. Closing this in the meantime.
